#!/usr/bin/env bash

# dotfiles
files=(
	./bash/bash_profile
	./bash/bashrc
	gitconfig
	latexmkrc
	zshrc
)

for file in "${files[@]}"; do 
	ln -snfv "$PWD/$file" "$HOME/.${file##*/}"
done

# neovim
ln -snfv "$HOME/.dotfiles/nvim" "$HOME/.config/nvim"

printf '\n\e[32minstallation complete\e[0m\n'
