#!/usr/bin/env bash


################
### Symlinks ###
################

# dotfiles
files=(
	bash/bash_profile
	bash/bashrc
	gitconfig
	latexmkrc
	zsh/zshrc
	omp-themes
)

for file in "${files[@]}"; do 
	ln -snfv "$PWD/$file" "$HOME/.${file##*/}"
done

# Neovim
ln -snfv "$HOME/.dotfiles/nvim" "$HOME/.config/nvim"

# Fastfetch
ln -snfv "$HOME/.dotfiles/fastfetch" "$HOME/.config/fastfetch"


####################
### Applications ###
####################

# Install oh my posh
if ! command -v oh-my-posh 2> /dev/null; then 
	curl -s https://ohmyposh.dev/install.sh | bash -s 
fi

printf '\n\e[32minstallation complete\e[0m\n'
